name: Upload to MinIO

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          npm run export  # only if you're using `next export`

          - name: Install AWS CLI
          run: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
        

      - name: Upload build to MinIO using AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        run: |
          aws configure set default.region us-east-1
          aws configure set default.output json

          aws s3 cp out/ s3://${{ secrets.MINIO_BUCKET }}/ --recursive \
            --endpoint-url ${{ secrets.MINIO_ENDPOINT }}